services:
  db:
    image: postgres:16-alpine
    container_name: jobtracker_db
    environment:
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: Jobpass
      POSTGRES_DB: jobtracker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U jobuser -d jobtracker"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  db_data:
    name: db_data
